/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;
/**
 *
 * @author HP
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calName1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        number1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        number2 = new javax.swing.JTextField();
        tru = new javax.swing.JButton();
        cong = new javax.swing.JButton();
        chia = new javax.swing.JButton();
        nhan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        result = new javax.swing.JLabel();

        calName1.setText("Welcome to Calculator !");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(70, 46, 0));
        setBounds(new java.awt.Rectangle(450, 200, 0, 0));
        setPreferredSize(new java.awt.Dimension(420, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("VNI-Bandit", 0, 18)); // NOI18N
        jLabel1.setText("Simple Calculator");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, -1));

        jLabel3.setFont(new java.awt.Font("Tektur", 0, 14)); // NOI18N
        jLabel3.setText("Kết Quả: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 20));

        number1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tektur", 0, 14)); // NOI18N
        jLabel4.setText("Số Thứ 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tektur", 0, 14)); // NOI18N
        jLabel5.setText("Số Thứ 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        number2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 130, -1));

        tru.setBackground(new java.awt.Color(102, 102, 102));
        tru.setFont(new java.awt.Font("Tektur", 0, 14)); // NOI18N
        tru.setForeground(new java.awt.Color(255, 255, 255));
        tru.setText("trừ");
        tru.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));
        tru.setBorderPainted(false);
        tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truActionPerformed(evt);
            }
        });
        getContentPane().add(tru, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 60, 30));

        cong.setBackground(new java.awt.Color(102, 102, 102));
        cong.setFont(new java.awt.Font("Tektur", 0, 14)); // NOI18N
        cong.setForeground(new java.awt.Color(255, 255, 255));
        cong.setText("cộng");
        cong.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));
        cong.setBorderPainted(false);
        cong.setFocusPainted(false);
        cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        getContentPane().add(cong, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 60, 30));

        chia.setBackground(new java.awt.Color(102, 102, 102));
        chia.setFont(new java.awt.Font("Tektur", 0, 14)); // NOI18N
        chia.setForeground(new java.awt.Color(255, 255, 255));
        chia.setText("chia");
        chia.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));
        chia.setBorderPainted(false);
        chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaActionPerformed(evt);
            }
        });
        getContentPane().add(chia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 60, 30));

        nhan.setBackground(new java.awt.Color(102, 102, 102));
        nhan.setFont(new java.awt.Font("Tektur", 0, 14)); // NOI18N
        nhan.setForeground(new java.awt.Color(255, 255, 255));
        nhan.setText("nhân");
        nhan.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));
        nhan.setBorderPainted(false);
        nhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanActionPerformed(evt);
            }
        });
        getContentPane().add(nhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 60, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tektur", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("reset");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 60, -1));

        jButton6.setBackground(new java.awt.Color(248, 248, 248));
        jButton6.setFont(new java.awt.Font("Tektur", 0, 13)); // NOI18N
        jButton6.setText("Thoát");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        result.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 140, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean CheckNumbers(){
        String n1 = number1.getText().trim();
        String n2 = number2.getText().trim();
        if(n1.isEmpty() || n2.isEmpty()){
            result.setText("Không đủ dữ liệu !");
            result.setForeground(Color.red);
            return false;
        }
        try{
            Double.parseDouble(n1);
            Double.parseDouble(n2);
            
        }catch( Exception e){
            result.setText("Sai kiểu dữ liệu !");
            result.setForeground(Color.red);
            return false;
        }
        
        return true;
    }
    private void number1FocusLost(java.awt.event.FocusEvent evt) {                                  
        CheckNumbers();
    }

    private void number2FocusLost(java.awt.event.FocusEvent evt) {                                  
        CheckNumbers();
    }
    private void truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truActionPerformed
        ButtonStyleClicked(tru);
        if(CheckNumbers() ==  true){
            double RS = Double.parseDouble(number1.getText()) - Double.parseDouble(number2.getText());
            if(RS % 1 == 0){
               result.setText(Integer.toString((int)RS));
               result.setForeground(Color.black);
            }else{
                result.setText(Double.toString(RS));
                result.setForeground(Color.black);
            } 
        }
    }//GEN-LAST:event_truActionPerformed

    private void congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congActionPerformed
        ButtonStyleClicked(cong);
        if(CheckNumbers() ==  true){
            double RS = Double.parseDouble(number1.getText()) + Double.parseDouble(number2.getText());
            if(RS % 1 == 0){
               result.setText(Integer.toString((int)RS));
               result.setForeground(Color.black);
            }else{
                result.setText(Double.toString(RS));
                result.setForeground(Color.black);
            } 
        }
    }//GEN-LAST:event_congActionPerformed

    private void chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaActionPerformed
       ButtonStyleClicked(chia);
       if(CheckNumbers() ==  true){
           if(Double.parseDouble(number2.getText()) == 0.0){
            result.setText("Không thể chia cho 0 !");
            result.setForeground(Color.red);
            }else{
                double RS = Double.parseDouble(number1.getText()) / Double.parseDouble(number2.getText());
                if(RS % 1 == 0){
                   result.setText(Integer.toString((int)RS));
                   result.setForeground(Color.black);
                }else{
                    result.setText(Double.toString(RS));
                    result.setForeground(Color.black);
                } 
            }
            
        }
    }//GEN-LAST:event_chiaActionPerformed

    private void nhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanActionPerformed
       ButtonStyleClicked(nhan);
       if(CheckNumbers() ==  true){
            double RS = Double.parseDouble(number1.getText()) * Double.parseDouble(number2.getText());
            if(RS % 1 == 0){
               result.setText(Integer.toString((int)RS));
               result.setForeground(Color.black);
               
            }else{
                result.setText(Double.toString(RS));
                result.setForeground(Color.black);
            } 
        }
    }//GEN-LAST:event_nhanActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setButtonDefaulStyle(tru);
        setButtonDefaulStyle(cong);
        setButtonDefaulStyle(nhan);
        setButtonDefaulStyle(chia);
        number1.setText("");
        number2.setText("");
        result.setText("");
        result.setForeground(Color.BLACK);
        jButton1.setFocusPainted(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void SetButtonClickedStyle(JButton button){
        button.setBackground(Color.WHITE);
        button.setForeground(Color.black);
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED,Color.BLACK, Color.white));
    }
    private void setButtonDefaulStyle(JButton button){
        button.setBackground(Color.DARK_GRAY);
        button.setForeground(Color.WHITE);
        button.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED,Color.BLACK, Color.white));
    }
    private void ButtonStyleClicked(JButton button){
        JButton[] allButtons = {tru, cong, nhan, chia};
        for (JButton btn : allButtons) {
            if (btn == button) {
                SetButtonClickedStyle(btn);
            }else{
                setButtonDefaulStyle(btn);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel calName1;
    private javax.swing.JButton chia;
    private javax.swing.JButton cong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton nhan;
    private javax.swing.JTextField number1;
    private javax.swing.JTextField number2;
    private javax.swing.JLabel result;
    private javax.swing.JButton tru;
    // End of variables declaration//GEN-END:variables
}
