package com.mycompany.cima;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RemoveCustomer = new javax.swing.JCheckBox();
        AddCustomer = new javax.swing.JCheckBox();
        SortWithDoSI = new javax.swing.JCheckBox();
        FindWithName = new javax.swing.JCheckBox();
        DisplayCustomer = new javax.swing.JCheckBox();
        FindWithId = new javax.swing.JCheckBox();
        SortWithDoB = new javax.swing.JCheckBox();
        UpdateCustomer = new javax.swing.JCheckBox();
        BreakCT = new javax.swing.JCheckBox();
        nameGroup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Information Management");

        jLabel1.setFont(new java.awt.Font("HP Simplified Hans Light", 1, 18)); // NOI18N
        jLabel1.setText("Customer information management !");

        RemoveCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RemoveCustomer.setText("Xóa Khách Hàng");
        RemoveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveCustomerActionPerformed(evt);
            }
        });

        AddCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddCustomer.setText("Thêm Khách Hàng");
        AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerActionPerformed(evt);
            }
        });

        SortWithDoSI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SortWithDoSI.setText("Sắp xếp khách hàng theo ngày đăng kí");
        SortWithDoSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortWithDoSIActionPerformed(evt);
            }
        });

        FindWithName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FindWithName.setText("Tìm kiếm khách hàng theo tên");
        FindWithName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindWithNameActionPerformed(evt);
            }
        });

        DisplayCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DisplayCustomer.setText("Hiển thị thông tin khách hàng");
        DisplayCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCustomerActionPerformed(evt);
            }
        });

        FindWithId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FindWithId.setText("Tìm kiếm khách hàng theo id");
        FindWithId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindWithIdActionPerformed(evt);
            }
        });

        SortWithDoB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SortWithDoB.setText("Sắp xếp khách hàng theo ngày sinh");
        SortWithDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortWithDoBActionPerformed(evt);
            }
        });

        UpdateCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateCustomer.setText("Sửa thông tin khách hàng");
        UpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCustomerActionPerformed(evt);
            }
        });

        BreakCT.setText("Thoát chương trình");
        BreakCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreakCTActionPerformed(evt);
            }
        });

        nameGroup.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        nameGroup.setText("gROUP 9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameGroup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BreakCT))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddCustomer)
                                            .addComponent(UpdateCustomer)
                                            .addComponent(RemoveCustomer))
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(DisplayCustomer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SortWithDoSI)
                                    .addComponent(SortWithDoB)
                                    .addComponent(FindWithName)
                                    .addComponent(FindWithId)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddCustomer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SortWithDoB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SortWithDoSI)
                    .addComponent(RemoveCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindWithName)
                    .addComponent(DisplayCustomer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateCustomer)
                    .addComponent(FindWithId))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BreakCT)
                    .addComponent(nameGroup))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveCustomerActionPerformed
        RemoveCustomer rc = new RemoveCustomer();
        rc.setVisible(true);
    }//GEN-LAST:event_RemoveCustomerActionPerformed

    private void BreakCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreakCTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BreakCTActionPerformed

    private void AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerActionPerformed
        AddCustomer ac = new AddCustomer();
        ac.setVisible(true);
    }//GEN-LAST:event_AddCustomerActionPerformed

    private void DisplayCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCustomerActionPerformed
        DisplayCustomer dc = new DisplayCustomer();
        dc.setVisible(true);
    }//GEN-LAST:event_DisplayCustomerActionPerformed

    private void UpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCustomerActionPerformed
        UpdateCustomer uc = new UpdateCustomer();
        uc.setVisible(true);
    }//GEN-LAST:event_UpdateCustomerActionPerformed

    private void SortWithDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortWithDoBActionPerformed
        SortWithDoB swdob = new SortWithDoB();
        swdob.setVisible(true);
    }//GEN-LAST:event_SortWithDoBActionPerformed

    private void SortWithDoSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortWithDoSIActionPerformed
        SortWithDoSI swdosi = new SortWithDoSI();
        swdosi.setVisible(true);
    }//GEN-LAST:event_SortWithDoSIActionPerformed

    private void FindWithNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindWithNameActionPerformed
        FindWithName fwn = new FindWithName();
        fwn.setVisible(true);
    }//GEN-LAST:event_FindWithNameActionPerformed

    private void FindWithIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindWithIdActionPerformed
        FindWithId fwi =  new FindWithId();
        fwi.setVisible(true);
    }//GEN-LAST:event_FindWithIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AddCustomer;
    private javax.swing.JCheckBox BreakCT;
    private javax.swing.JCheckBox DisplayCustomer;
    private javax.swing.JCheckBox FindWithId;
    private javax.swing.JCheckBox FindWithName;
    private javax.swing.JCheckBox RemoveCustomer;
    private javax.swing.JCheckBox SortWithDoB;
    private javax.swing.JCheckBox SortWithDoSI;
    private javax.swing.JCheckBox UpdateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameGroup;
    // End of variables declaration//GEN-END:variables
}
